# Workshop Network of Terms

# Look up the resource description of a URI (harmonized in SKOS)
query {
  lookup(
    uris: ["https://data.muziekweb.nl/Link/M00000086786"],
  ) {
    uri
    source {
      ... on Source {
        uri
        name
      }
      ... on Error {
        __typename
        message
      }
    }
    result {
      ... on Term {
        uri
        prefLabel
        scopeNote
      }
      ... on Error {
        __typename
        message
      }
    }
    responseTimeMs
  }
}