PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX bif: <http://www.openlinksw.com/schemas/bif#>
PREFIX dbo: <http://dbpedia.org/ontology/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

CONSTRUCT {
    ?uri a skos:Concept ;
        skos:prefLabel ?label ;
        skos:scopeNote ?abstract .
}
WHERE {
  ?uri rdfs:label ?label ;
     dbo:abstract ?abstract ;
     rdf:type dbo:Person .
  ?label <bif:contains> ?virtuosoQuery
  FILTER(LANG(?label)="en")
  FILTER(LANG(?abstract)="en")
} LIMIT 1000